coverage:
    status:
        project:
            default:
                target: 50%
        patch:
            default:
                target: 50%
comment:
    layout: 'condensed_header, condensed_files, condensed_footer'
    hide_project_coverage: true
